/*-
 * WSDL stubs for:  http://localhost:8080/AnimalsWebService/services/AnimalsDBManagement?wsdl
 *   Generated by:  VIKO
 *           Date:  Tue Oct 25 20:01:00 2011
 *        Emitter:  Objective-C
 */

#import "AnimalsDBWebService.h"

/*-
 *   Method Name:  getAnimalsFromCity
 * Documentation:  <no documentation>
 */
@implementation getAnimalsFromCity
- (void) setParameters:(CFTypeRef /* Complex type http://database.java.insaneplatypusgames.com|getAnimalsFromCity */) in_parameters
{
    id _paramValues[] = {    
        in_parameters,        
    };    
    NSString* _paramNames[] = {    
        @"parameters",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"parameters"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://localhost:8080/AnimalsWebService/services/AnimalsDBManagement.AnimalsDBManagementHttpEndpoint/"            
                 methodName: @"getAnimalsFromCity"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
            // missing encoding style - defaulting to RPC            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: nil /* No SOAPAction header needed */            
            methodNamespace: NULL /* No Method Namespace specified */            
        ];        
}

@end; /* getAnimalsFromCity */


/*-
 *   Method Name:  createTable
 * Documentation:  <no documentation>
 */
@implementation createTable
- (void) setParameters:(CFTypeRef /* Complex type http://database.java.insaneplatypusgames.com|createTable */) in_parameters
{
    id _paramValues[] = {    
        in_parameters,        
    };    
    NSString* _paramNames[] = {    
        @"parameters",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://localhost:8080/AnimalsWebService/services/AnimalsDBManagement.AnimalsDBManagementHttpEndpoint/"            
                 methodName: @"createTable"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
            // missing encoding style - defaulting to RPC            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: nil /* No SOAPAction header needed */            
            methodNamespace: NULL /* No Method Namespace specified */            
        ];        
}

@end; /* createTable */


/*-
 *   Method Name:  insertAnimal
 * Documentation:  <no documentation>
 */
@implementation insertAnimal
- (void) setParameters:(CFTypeRef /* Complex type http://database.java.insaneplatypusgames.com|insertAnimal */) in_parameters
{
    id _paramValues[] = {    
        in_parameters,        
    };    
    NSString* _paramNames[] = {    
        @"parameters",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://localhost:8080/AnimalsWebService/services/AnimalsDBManagement.AnimalsDBManagementHttpEndpoint/"            
                 methodName: @"insertAnimal"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
            // missing encoding style - defaulting to RPC            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: nil /* No SOAPAction header needed */            
            methodNamespace: NULL /* No Method Namespace specified */            
        ];        
}

@end; /* insertAnimal */


/*-
 *   Method Name:  getAnimalsFromCity
 * Documentation:  <no documentation>
 */
@implementation getAnimalsFromCity
- (void) setParameters:(CFTypeRef /* Complex type http://database.java.insaneplatypusgames.com|getAnimalsFromCity */) in_parameters
{
    id _paramValues[] = {    
        in_parameters,        
    };    
    NSString* _paramNames[] = {    
        @"parameters",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"parameters"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://localhost:8080/AnimalsWebService/services/AnimalsDBManagement.AnimalsDBManagementHttpSoap11Endpoint/"            
                 methodName: @"getAnimalsFromCity"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:getAnimalsFromCity"            
            methodNamespace: NULL /* No Method Namespace specified */            
        ];        
}

@end; /* getAnimalsFromCity */


/*-
 *   Method Name:  createTable
 * Documentation:  <no documentation>
 */
@implementation createTable
- (void) setParameters:(CFTypeRef /* Complex type http://database.java.insaneplatypusgames.com|createTable */) in_parameters
{
    id _paramValues[] = {    
        in_parameters,        
    };    
    NSString* _paramNames[] = {    
        @"parameters",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://localhost:8080/AnimalsWebService/services/AnimalsDBManagement.AnimalsDBManagementHttpSoap11Endpoint/"            
                 methodName: @"createTable"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:createTable"            
            methodNamespace: NULL /* No Method Namespace specified */            
        ];        
}

@end; /* createTable */


/*-
 *   Method Name:  insertAnimal
 * Documentation:  <no documentation>
 */
@implementation insertAnimal
- (void) setParameters:(CFTypeRef /* Complex type http://database.java.insaneplatypusgames.com|insertAnimal */) in_parameters
{
    id _paramValues[] = {    
        in_parameters,        
    };    
    NSString* _paramNames[] = {    
        @"parameters",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://localhost:8080/AnimalsWebService/services/AnimalsDBManagement.AnimalsDBManagementHttpSoap11Endpoint/"            
                 methodName: @"insertAnimal"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:insertAnimal"            
            methodNamespace: NULL /* No Method Namespace specified */            
        ];        
}

@end; /* insertAnimal */


/*-
 *   Method Name:  getAnimalsFromCity
 * Documentation:  <no documentation>
 */
@implementation getAnimalsFromCity
- (void) setParameters:(CFTypeRef /* Complex type http://database.java.insaneplatypusgames.com|getAnimalsFromCity */) in_parameters
{
    id _paramValues[] = {    
        in_parameters,        
    };    
    NSString* _paramNames[] = {    
        @"parameters",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"parameters"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://localhost:8080/AnimalsWebService/services/AnimalsDBManagement.AnimalsDBManagementHttpSoap12Endpoint/"            
                 methodName: @"getAnimalsFromCity"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:getAnimalsFromCity"            
            methodNamespace: NULL /* No Method Namespace specified */            
        ];        
}

@end; /* getAnimalsFromCity */


/*-
 *   Method Name:  createTable
 * Documentation:  <no documentation>
 */
@implementation createTable
- (void) setParameters:(CFTypeRef /* Complex type http://database.java.insaneplatypusgames.com|createTable */) in_parameters
{
    id _paramValues[] = {    
        in_parameters,        
    };    
    NSString* _paramNames[] = {    
        @"parameters",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://localhost:8080/AnimalsWebService/services/AnimalsDBManagement.AnimalsDBManagementHttpSoap12Endpoint/"            
                 methodName: @"createTable"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:createTable"            
            methodNamespace: NULL /* No Method Namespace specified */            
        ];        
}

@end; /* createTable */


/*-
 *   Method Name:  insertAnimal
 * Documentation:  <no documentation>
 */
@implementation insertAnimal
- (void) setParameters:(CFTypeRef /* Complex type http://database.java.insaneplatypusgames.com|insertAnimal */) in_parameters
{
    id _paramValues[] = {    
        in_parameters,        
    };    
    NSString* _paramNames[] = {    
        @"parameters",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://localhost:8080/AnimalsWebService/services/AnimalsDBManagement.AnimalsDBManagementHttpSoap12Endpoint/"            
                 methodName: @"insertAnimal"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:insertAnimal"            
            methodNamespace: NULL /* No Method Namespace specified */            
        ];        
}

@end; /* insertAnimal */



@implementation AnimalsDBManagementService

+ (id) getAnimalsFromCity:(CFTypeRef /* Complex type http://database.java.insaneplatypusgames.com|getAnimalsFromCity */) in_parameters
{
    id result = NULL;    
    getAnimalsFromCity* _invocation = [[getAnimalsFromCity alloc] init];    
    [_invocation setParameters: in_parameters];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) createTable:(CFTypeRef /* Complex type http://database.java.insaneplatypusgames.com|createTable */) in_parameters
{
    id result = NULL;    
    createTable* _invocation = [[createTable alloc] init];    
    [_invocation setParameters: in_parameters];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) insertAnimal:(CFTypeRef /* Complex type http://database.java.insaneplatypusgames.com|insertAnimal */) in_parameters
{
    id result = NULL;    
    insertAnimal* _invocation = [[insertAnimal alloc] init];    
    [_invocation setParameters: in_parameters];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}



@end;


/*-
 * End of WSDL document at
 * http://localhost:8080/AnimalsWebService/services/AnimalsDBManagement?wsdl
 */
